# Generated by Django 4.1.4 on 2022-12-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_info_got_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='got_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.info')),
            ],
        ),
        migrations.CreateModel(
            name='got_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.got_address')),
            ],
        ),
        migrations.CreateModel(
            name='got_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.got_date')),
            ],
        ),
    ]
