# Generated by Django 4.1.4 on 2023-01-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_radio_btn_check_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='test_program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='test_sponsor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='test_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
